<?php
// Content used until the site is first saved from the admin panel.

return [
    'settings' => [
        'site_name' => 'Lumen',
        'page_title' => 'Lumen — Build Better, Faster',
        'meta_description' => 'Lumen helps teams plan, build and ship great work.',
        'primary_color' => '#5b5bf6',
        'accent_color' => '#14b8a6',
        'currency' => '$',
        'footer_tagline' => 'Build better products, faster.',
        'copyright_name' => 'Lumen, Inc.',
        'notify_email' => '',
    ],
    'hero' => [
        'eyebrow' => 'New · Version 2.0 is here',
        'title' => 'Build better products,',
        'title_highlight' => 'faster.',
        'lead' => "Lumen brings your team's planning, building and shipping into one calm, focused workspace — so you can spend less time managing work and more time doing it.",
        'primary_label' => 'Start free trial',
        'primary_link' => '#pricing',
        'secondary_label' => 'See how it works →',
        'secondary_link' => '#features',
        'fine_print' => 'No credit card required · Cancel anytime',
    ],
    'logos' => [
        'visible' => true,
        'heading' => 'Trusted by teams at',
        'names' => ['Northpeak', 'Brightline', 'Orbital', 'Fernwood', 'Quanta'],
    ],
    'features' => [
        'visible' => true,
        'nav_label' => 'Features',
        'eyebrow' => 'Features',
        'heading' => "Everything you need, nothing you don't",
        'subheading' => 'Thoughtfully designed tools that stay out of your way.',
        'items' => [
            ['icon' => '⚡', 'title' => 'Lightning fast', 'text' => 'Every interaction feels instant. No spinners, no waiting — just flow.'],
            ['icon' => '🔒', 'title' => 'Secure by default', 'text' => 'End-to-end encryption, SSO and granular permissions out of the box.'],
            ['icon' => '🤝', 'title' => 'Built for teams', 'text' => 'Real-time collaboration, comments and mentions keep everyone aligned.'],
            ['icon' => '📊', 'title' => 'Insightful analytics', 'text' => "Clear dashboards show what's working and where to focus next."],
            ['icon' => '🔌', 'title' => 'Integrations', 'text' => 'Connect the tools you already use with 100+ one-click integrations.'],
            ['icon' => '📱', 'title' => 'Works everywhere', 'text' => 'Desktop, web and mobile apps that stay perfectly in sync.'],
        ],
    ],
    'about' => [
        'visible' => true,
        'nav_label' => 'About',
        'eyebrow' => 'About us',
        'heading' => 'Made by a small team that cares about craft',
        'body' => "We started Lumen because we were tired of tools that got in the way. Since then we've helped thousands of teams around the world do their best work — and we're just getting started.",
        'checklist' => ['Independent and customer-funded', 'Remote-first across 12 countries', 'Carbon-neutral infrastructure'],
        'stats' => [
            ['value' => '12000', 'suffix' => '+', 'label' => 'Teams'],
            ['value' => '99.9', 'suffix' => '%', 'label' => 'Uptime'],
            ['value' => '140', 'suffix' => '+', 'label' => 'Countries'],
            ['value' => '4.9', 'suffix' => '/5', 'label' => 'Avg. rating'],
        ],
    ],
    'testimonials' => [
        'visible' => true,
        'nav_label' => 'Testimonials',
        'eyebrow' => 'Testimonials',
        'heading' => 'Loved by people who ship',
        'items' => [
            ['quote' => 'Lumen replaced three tools for us overnight. Our weekly planning meeting went from an hour to fifteen minutes.', 'name' => 'Alex Rivera', 'role' => 'Head of Product, Northpeak'],
            ['quote' => "The fastest, cleanest tool we've used. Onboarding the whole company took an afternoon.", 'name' => 'Jordan Kim', 'role' => 'CTO, Orbital'],
            ['quote' => 'Finally, software that respects my time. I genuinely enjoy opening it every morning.', 'name' => 'Sam Patel', 'role' => 'Designer, Fernwood'],
        ],
    ],
    'pricing' => [
        'visible' => true,
        'nav_label' => 'Pricing',
        'eyebrow' => 'Pricing',
        'heading' => 'Simple, transparent pricing',
        'yearly_badge' => 'Save 20%',
        'plans' => [
            ['name' => 'Starter', 'description' => 'For individuals getting started.', 'monthly' => '0', 'yearly' => '0', 'features' => ['Up to 3 projects', 'Basic analytics', 'Community support'], 'cta_label' => 'Get started', 'cta_link' => '#contact', 'featured' => false, 'tag' => ''],
            ['name' => 'Pro', 'description' => 'For growing teams that need more.', 'monthly' => '19', 'yearly' => '15', 'features' => ['Unlimited projects', 'Advanced analytics', 'Priority support', 'All integrations'], 'cta_label' => 'Start free trial', 'cta_link' => '#contact', 'featured' => true, 'tag' => 'Most popular'],
            ['name' => 'Enterprise', 'description' => 'For organizations at scale.', 'monthly' => '49', 'yearly' => '39', 'features' => ['Everything in Pro', 'SSO & audit logs', 'Dedicated manager', 'Custom contracts'], 'cta_label' => 'Contact sales', 'cta_link' => '#contact', 'featured' => false, 'tag' => ''],
        ],
    ],
    'faq' => [
        'visible' => true,
        'nav_label' => '',
        'eyebrow' => 'FAQ',
        'heading' => 'Frequently asked questions',
        'items' => [
            ['question' => 'Is there a free trial?', 'answer' => 'Yes — every paid plan comes with a 14-day free trial. No credit card required.'],
            ['question' => 'Can I change plans later?', 'answer' => 'Absolutely. Upgrade, downgrade or cancel at any time from your account settings.'],
            ['question' => 'Do you offer discounts for nonprofits?', 'answer' => 'We do. Nonprofits and educational institutions get 50% off any plan.'],
            ['question' => 'Where is my data stored?', 'answer' => 'Data is stored in secure, SOC 2 compliant data centers with daily encrypted backups.'],
        ],
    ],
    'contact' => [
        'visible' => true,
        'nav_label' => 'Get in touch',
        'eyebrow' => 'Contact',
        'heading' => "Let's talk",
        'body' => "Have a question or want a demo? Send us a message and we'll get back to you within one business day.",
        'email' => 'hello@example.com',
        'phone' => '(555) 123-4567',
        'address' => '123 Main Street, Anytown',
        'button_label' => 'Send message',
        'success_message' => "Thanks! We'll be in touch soon.",
    ],
    'newsletter' => [
        'visible' => true,
        'heading' => 'Stay updated',
        'placeholder' => 'you@example.com',
        'button_label' => 'Subscribe',
    ],
];
